apiVersion: kubeaddons.mesosphere.io/v1beta1
kind: ClusterAddon
metadata:
  annotations:
    appversion.kubeaddons.mesosphere.io/knative: 0.18.3
    catalog.kubeaddons.mesosphere.io/addon-revision: 0.18.3-1
    values.chart.helm.kubeaddons.mesosphere.io/knative: "https://raw.githubusercontent.com/mesosphere/charts/master/staging/knative/values.yaml"
  labels:
    kubeaddons.mesosphere.io/name: knative
  name: knative
  namespace: kubeaddons
spec:
  kubernetes:
    minSupportedVersion: v1.17.0
  cloudProvider:
    - name: aws
      enabled: false
    - name: azure
      enabled: false
    - name: docker
      enabled: false
    - name: none
      enabled: false
  chartReference:
    chart: knative
    repo: https://github.com/mesosphere/charts/tree/upgrade-knnative-serving-0.18.3/staging
    version: 0.3.5
    values: |
      eventing:
        enabled: false
      eventing-sources:
        enabled: false
      serving:
        enabled: true
        customMetricsApiservice:
          enabled: false
        namespaceKnativeServing:
          additionalLabels:
            ca.istio.io/override: "true"
